name             'cheftdd'
maintainer       'Simone Soldateschi'
maintainer_email 'simone.soldateschi@gmail.com'
license          'GNU General Public License v3+'
description      'Installs/Configures cheftdd'
long_description 'Installs/Configures cheftdd'
version          '0.1.0'

depends 'apt'
depends 'nodejs'
depends 'platformstack'
