name             'cheftdd'
maintainer       'Simone Soldateschi'
maintainer_email 'simone.soldateschi@gmail.com'
license          'All rights reserved'
description      'Installs/Configures cheftdd'
long_description 'Installs/Configures cheftdd'
version          '0.1.0'
